### ISSUE TITLE
xml filter xpath crashes on logstash 5.6 starting at 5.6.15 

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-filter-xml#63]
Problem desciption in elastic/logstash#11068

Basically logstash 5.6.15 introduced dependency on nokogiri 1.9.1 which in incompatible with JRuby 1.7.27 used in logstash 5.6

the problem has been reported when using the `xpath` option.

To reproduce:

```
bin/logstash -e 'filter {xml { source => "message" store_xml => "false" xpath => ["/xml/tag/text()", "StartText"]}}'
...
<xml><tag>value</tag></xml>
```

which result in
```
2019-08-21T14:38:22,143][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"org.jruby.RubyFixnum.getIntValue()I", "backtrace"=>["nokogiri.XmlNodeSet.slice(XmlNodeSet.java:341)", "nokogiri.XmlNodeSet$INVOKER$i$slice.call(XmlNodeSet$INVOKER$i$slice.gen)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)", "org.jruby.ast.YieldOneNode.interpret(YieldOneNode.java:35)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)", "org.jruby.runtime.Block.yield(Block.java:142)", "org.jruby.RubyInteger.fixnumUpto(RubyInteger.java:161)", "org.jruby.RubyInteger.upto(RubyInteger.java:133)", "org.jruby.RubyInteger$INVOKER$i$1$0$upto.call(RubyInteger$INVOKER$i$1$0$upto.gen)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:161)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:195)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)", "org.jruby.runtime.Block.yield(Block.java:142)", "org.jruby.RubyHash$13.visit(RubyHash.java:1355)", "org.jruby.RubyHash.visitLimited(RubyHash.java:648)", "org.jruby.RubyHash.visitAll(RubyHash.java:634)", "org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1306)", "org.jruby.RubyHash.each_pairCommon(RubyHash.java:1351)", "org.jruby.RubyHash.each19(RubyHash.java:1342)", "org.jruby.RubyHash$INVOKER$i$0$0$each19.call(RubyHash$INVOKER$i$0$0$each19.gen)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.IfNode.interpret(IfNode.java:116)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)", "org.jruby.ast.FCallOneArgBlockPassNode.interpret(FCallOneArgBlockPassNode.java:32)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "rubyjit.LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c4521685669.block_0$RUBY$__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filters/base.rb:164)", "rubyjit$LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c4521685669$block_0$RUBY$__file__.call(rubyjit$LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c4521685669$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.Block.yield(Block.java:142)", "org.jruby.RubyArray.eachCommon(RubyArray.java:1606)", "org.jruby.RubyArray.each(RubyArray.java:1613)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c4521685669.__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filters/base.rb:161)", "rubyjit.LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c4521685669.__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filters/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.LogStash::FilterDelegator$$multi_filter_ef4a51fe741f6dcc5a05ed6b3a19f6e15142a76821685669.__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filter_delegator.rb:46)", "rubyjit.LogStash::FilterDelegator$$multi_filter_ef4a51fe741f6dcc5a05ed6b3a19f6e15142a76821685669.__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filter_delegator.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)", "org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)", "org.jruby.runtime.Block.call(Block.java:101)", "org.jruby.RubyProc.call(RubyProc.java:300)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.LogStash::Pipeline$$filter_batch_052b78d27259f9bcbc13f5e343ec3d67811edf0321685669.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/pipeline.rb:398)", "rubyjit.LogStash::Pipeline$$filter_batch_052b78d27259f9bcbc13f5e343ec3d67811edf0321685669.__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/pipeline.rb)", "rubyjit.LogStash::Pipeline$$filter_batch_052b78d27259f9bcbc13f5e343ec3d67811edf0321685669.__file__(/Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/pipeline.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.WhileNode.interpret(WhileNode.java:131)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)", "org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)", "org.jruby.runtime.Block.call(Block.java:101)", "org.jruby.RubyProc.call(RubyProc.java:300)", "org.jruby.RubyProc.call(RubyProc.java:230)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:103)", "java.lang.Thread.run(Thread.java:748)"]}
XmlNodeSet.java:341:in `slice': java.lang.NoSuchMethodError: org.jruby.RubyFixnum.getIntValue()I
	from XmlNodeSet$INVOKER$i$slice.gen:-1:in `call'
	from CachingCallSite.java:326:in `cacheAndCall'
	from CachingCallSite.java:170:in `call'
	from FCallOneArgNode.java:36:in `interpret'
	from YieldOneNode.java:35:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
	from Interpreted19Block.java:206:in `evalBlockBody'
	from Interpreted19Block.java:157:in `yield'
	from Block.java:142:in `yield'
	from RubyInteger.java:161:in `fixnumUpto'
	from RubyInteger.java:133:in `upto'
	from RubyInteger$INVOKER$i$1$0$upto.gen:-1:in `call'
	from CachingCallSite.java:336:in `cacheAndCall'
	from CachingCallSite.java:179:in `callBlock'
	from CachingCallSite.java:188:in `callIter'
	from CallOneArgBlockNode.java:60:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:161:in `call'
	from DefaultMethod.java:195:in `call'
	from CachingCallSite.java:316:in `cacheAndCall'
	from CachingCallSite.java:145:in `callBlock'
	from CachingCallSite.java:154:in `callIter'
	from CallNoArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
	from Interpreted19Block.java:206:in `evalBlockBody'
	from Interpreted19Block.java:157:in `yield'
	from Block.java:142:in `yield'
	from RubyHash.java:1355:in `visit'
	from RubyHash.java:648:in `visitLimited'
	from RubyHash.java:634:in `visitAll'
	from RubyHash.java:1306:in `iteratorVisitAll'
	from RubyHash.java:1351:in `each_pairCommon'
	from RubyHash.java:1342:in `each19'
	from RubyHash$INVOKER$i$0$0$each19.gen:-1:in `call'
	from CachingCallSite.java:316:in `cacheAndCall'
	from CachingCallSite.java:145:in `callBlock'
	from CachingCallSite.java:154:in `callIter'
	from CallNoArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from IfNode.java:116:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:204:in `call'
	from DefaultMethod.java:211:in `call'
	from CachingCallSite.java:336:in `cacheAndCall'
	from CachingCallSite.java:179:in `callBlock'
	from CachingCallSite.java:183:in `call'
	from FCallOneArgBlockPassNode.java:32:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:204:in `call'
	from DefaultMethod.java:211:in `call'
	from CachingCallSite.java:336:in `cacheAndCall'
	from CachingCallSite.java:179:in `callBlock'
	from CachingCallSite.java:188:in `callIter'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filters/base.rb:164:in `block_0$RUBY$__file__'
	from rubyjit$LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c4521685669$block_0$RUBY$__file__:-1:in `call'
	from CompiledBlock19.java:135:in `yield'
	from Block.java:142:in `yield'
	from RubyArray.java:1606:in `eachCommon'
	from RubyArray.java:1613:in `each'
# This is a Logstash generated Gemfile.
	from RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'
	from CachingCallSite.java:143:in `callBlock'
	from CachingCallSite.java:154:in `callIter'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filters/base.rb:161:in `__file__'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filters/base.rb:-1:in `__file__'
	from JittedMethod.java:181:in `call'
	from CachingCallSite.java:168:in `call'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filter_delegator.rb:46:in `__file__'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/filter_delegator.rb:-1:in `__file__'
	from JittedMethod.java:181:in `call'
	from CachingCallSite.java:168:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from DAsgnNode.java:110:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
	from Interpreted19Block.java:206:in `evalBlockBody'
	from Interpreted19Block.java:194:in `yield'
	from Interpreted19Block.java:125:in `call'
	from Block.java:101:in `call'
	from RubyProc.java:300:in `call'
	from ProcMethod.java:64:in `call'
	from DynamicMethod.java:210:in `call'
	from DynamicMethod.java:206:in `call'
	from CachingCallSite.java:168:in `call'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/pipeline.rb:398:in `chained_0_rescue_1$RUBY$SYNTHETIC__file__'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/pipeline.rb:-1:in `__file__'
	from /Users/colin/dev/src/elasticsearch/logstash/tmp/logstash-5.6.16/logstash-core/lib/logstash/pipeline.rb:-1:in `__file__'
	from JittedMethod.java:181:in `call'
	from CachingCallSite.java:168:in `call'
	from FCallOneArgNode.java:36:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from WhileNode.java:131:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:225:in `call'
	from DefaultMethod.java:219:in `call'
	from CachingCallSite.java:202:in `call'
	from FCallTwoArgNode.java:38:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
	from Interpreted19Block.java:206:in `evalBlockBody'
	from Interpreted19Block.java:194:in `yield'
	from Interpreted19Block.java:125:in `call'
	from Block.java:101:in `call'
	from RubyProc.java:300:in `call'
	from RubyProc.java:230:in `call'
	from RubyRunnable.java:103:in `run'
	from Thread.java:748:in `run'
```

**Comment by kares** [comment]
just an update for anyone landing here: the problem was Nokogiri **(~>) 1.9.0** forgot to specify the `required_ruby_version >= 2.3` for the JRuby specific version of the gem. 
last Nokogiri version known to be compatible with JRuby 1.7 was Nokogiri **1.8.5**.

**Comment by kares** [comment]
since LS 5.6 is lo longer supported and the Nokogiri issue only concerns JRuby 1.7
... this issue should be tagged as wontfix and closed?

**Comment by colinsurprenant** [comment]
If anyone stumble of this and can't upgrade this is a workaround:

- Edit `Gemfile` and change 
```
gem "nokogiri", "~> 1.9.1"
```
to 
```
gem "nokogiri", "~> 1.8.5"
```
then run
```
$ bin/logstash-plugin update logstash-filter-xml
```

This will downgrade the nokogiri gem from version 1.9.1 to 1.8.5 and resolves the issue.
