### ISSUE TITLE
Swap xmlsimple for nori?

### ISSUE THREAD

**Issue by johnwards** [logstash-plugins/logstash-filter-xml#7]
Hey, so I'm parsing some XML that our log system generates. The data structure that xmlsimple returns isn't nice to work with to say the least. I've been playing with different xml parsers today and I'm much happier with the output from Nori. https://github.com/savonrb/nori

XMLSimple:

```
<hello><foo>12</foo><bar></bar></hello>
{
       "message" => "<hello><foo>12</foo><bar></bar></hello>",
      "@version" => "1",
    "@timestamp" => "2015-01-28T14:49:02.343Z",
          "host" => "Johns-MacBook-Air.local",
           "xml" => {
        "foo" => [
            [0] "12"
        ],
        "bar" => [
            [0] {}
        ]
    }
}
```

Nori:

```
<hello><foo>12</foo><bar></bar></hello>
{
       "message" => "<hello><foo>12</foo><bar></bar></hello>",
      "@version" => "1",
    "@timestamp" => "2015-01-28T14:41:47.515Z",
          "host" => "Johns-MacBook-Air.local",
           "xml" => {
        "hello" => {
            "foo" => "12",
            "bar" => nil
        }
    }
}
```

It was very straightforward to add, but I guess it is a BC break in terms of the XML response...

What are your thoughts about this? Should I just create my own plugin to do this?

**Comment by jsvd** [comment]
Not sure what's happening here but this breaks current version of the plugin/logstash

```
/tmp/logstash-1.5.4 % echo "<hello><foo>12</foo><bar></bar></hello>" | bin/logstash -e "input { stdin { codec => plain } } filter { xml { source => 'message' } } output { stdout { codec => rubydebug } }"
Logstash startup completed
Trouble parsing xml with XmlSimple {:source=>"message", :value=>"<hello><foo>12</foo><bar></bar></hello>", :exception=>#<NoMethodError: undefined method `start_with?' for nil:NilClass>, :backtrace=>["/tmp/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/event.rb:140:in `[]='", "/tmp/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-filter-xml-1.0.0/lib/logstash/filters/xml.rb:129:in `filter'", "/tmp/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:163:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/tmp/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:160:in `multi_filter'", "(eval):41:in `filter_func'", "/tmp/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/tmp/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:157:in `start_filters'"], :level=>:warn}
{
       "message" => "<hello><foo>12</foo><bar></bar></hello>",
      "@version" => "1",
    "@timestamp" => "2015-09-04T13:26:11.839Z",
          "host" => "Joaos-MBP.lan",
          "tags" => [
        [0] "_xmlparsefailure"
    ]
}
```

**Comment by wiibaa** [comment]
The filter can now provide similar output with the following plugin settings
````
  force_array => false
  supress_empty => true
````
The only difference is that it will currently drop empty tag like `<bar></bar>` instead of setting null.
Because I'm not sure there are real cases within the logstash users to process this `bar => nil` kind of field I would close this issue and wait for the specific request to handle them this way.

@jsvd @suyograo ok to close ?

**Comment by guyboertje** [comment]
@wiibaa - somewhat late reply. Yes, closing on your behalf.
